# <span style = 'color: #00adee'> Hospital Admission Data

Information on alcohol and drug-related hospital admissions are obtained from the Victorian Admitted Episodes Dataset (VAED).

In [1]:
import numpy as np
import pandas as pd
vaed_nov = pd.read_csv('C:/Users/Emma.Zhang/OneDrive - Melbourne Primary Care Network/Documents/Needs Assessment/AOD/PHN_2021_Nov/PHN_VAED2021_Nov_20201217.txt', engine = 'python', delimiter='\t')
vaed_dec = pd.read_csv('C:/Users/Emma.Zhang/OneDrive - Melbourne Primary Care Network/Documents/Needs Assessment/AOD/PHN_2021_Dec/PHN_VAED2021_Dec_20210119.txt', engine = 'python', delimiter='\t')
VAED_DEC = vaed_dec[vaed_dec['Care_Type'] == '0']
VAED_NOV = vaed_nov[vaed_nov['Care_Type'] == '0']
lga = pd.read_csv('C:/Users/Emma.Zhang/OneDrive - Melbourne Primary Care Network/Documents/Needs Assessment/AOD/AOD JB/12160_Local_Government_Area_Structure.csv')

Episodes care type is "Alcohol and drug' program

In [2]:
VAED_NOV

,UniqueID,FY,CAMPUS,Care_Type,TenYearAgeGroups,EMNL,Int_Duration_Stay,ADMBARTH,READMREH,SEPBARTH,...,Block31,Block32,Block33,Block34,Block35,Block36,Block37,Block38,Block39,Block40
133787,44202058,2020/21,2320,0,30-39,E,Overnight or longer,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134113,44202386,2020/21,2320,0,40-49,E,Overnight or longer,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134406,44202680,2020/21,2320,0,50-59,E,Overnight or longer,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134498,44202772,2020/21,2320,0,40-49,E,Overnight or longer,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134735,44203009,2020/21,2320,0,40-49,E,Overnight or longer,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
300995,44399084,2020/21,2320,0,50-59,E,Overnight or longer,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
301470,44399559,2020/21,2320,0,30-39,E,Overnight or longer,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
302234,44400323,2020/21,2320,0,50-59,E,Overnight or longer,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
357515,44477558,2020/21,2320,0,30-39,E,Overnight or longer,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
358477,44478520,2020/21,2320,0,60-69,E,Overnight or longer,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
553344,44780043,2020/21,2320,0,20-29,E,Overnight or longer,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
681835,45002634,2020/21,2320,0,20-29,E,Overnight or longer,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
682228,45003028,2020/21,2320,0,40-49,E,Overnight or longer,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

```[note]
Incomplete data?
```